  name: remote ssh command
  on: [push]
  jobs:
    build:
      name: Build
      runs-on: ubuntu-latest
      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.3
          with:
            host: ${{ variables.HOST }}
            username: ${{ variables.USERNAME }}
            key: ${{ variables.KEY }}
            port: ${{ variables.PORT }}
            script: |
              cd /var/www/html
              git pull      
